# This is the configuration used to check the rubocop source code.

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
  TargetRubyVersion: 2.0

Style/Encoding:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/LambdaCall:
  Exclude:
    - '*.jbuilder'
